export const sidebarItem = [
  {
    label: "Home",
    icon: "AiFillAmazonCircle",
    link: "/home",
    type: "child menu",
    childrenArr: [
      {
        label: "Progress",
        icon: "<svg></svg>",
        link: "/home",
        type: "child menu",
        childrenArr: [],
      },
      {
        label: "Team members",
        icon: "<svg></svg>",
        link: "/home",
        type: "child menu",
        childrenArr: [],
      },
      {
        label: "All task",
        icon: "<svg></svg>",
        link: "/home",
        type: "child menu",
        childrenArr: [],
      },
      {
        label: "In Review",
        icon: "<svg></svg>",
        link: "/home",
        type: "child menu",
        childrenArr: [],
      },
      {
        label: "In Progress",
        icon: "<svg></svg>",
        link: "/home",
        type: "child menu",
        childrenArr: [],
      },
      {
        label: "Next Up",
        icon: "<svg></svg>",
        link: "/home",
        type: "child menu",
        childrenArr: [],
      },
    ],
  },
  {
    label: "Home",
    icon: "AiFillAmazonCircle",
    link: "/home",
    type: "child menu",
    childrenArr: [
      {
        label: "Progress",
        icon: "<svg></svg>",
        link: "/home",
        type: "child menu",
        childrenArr: [],
      },
      {
        label: "Team members",
        icon: "<svg></svg>",
        link: "/home",
        type: "child menu",
        childrenArr: [],
      },
      {
        label: "All task",
        icon: "<svg></svg>",
        link: "/home",
        type: "child menu",
        childrenArr: [],
      },
      {
        label: "In Review",
        icon: "<svg></svg>",
        link: "/home",
        type: "child menu",
        childrenArr: [],
      },
      {
        label: "In Progress",
        icon: "<svg></svg>",
        link: "/home",
        type: "child menu",
        childrenArr: [],
      },
      {
        label: "Next Up",
        icon: "<svg></svg>",
        link: "/home",
        type: "child menu",
        childrenArr: [],
      },
    ],
  },
];
